# Use root/example as user/password credentials
version: '3.1'

services:
  shard0:
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/shard0/data:/var/lib/mysql
      - ./database/shard0/migrations:/docker-entrypoint-initdb.d # auto runs on startup
    ports:
      - '3001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: shard0

  shard1:
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/shard1/data:/var/lib/mysql
      - ./database/shard1/migrations:/docker-entrypoint-initdb.d # auto runs on startup
    ports:
      - '3002:3307'
    environment:
      MYSQL_ROOT_PASSWORD: shard1
      MYSQL_TCP_PORT: 3307

  api:
    image: foo
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - shard0
      - shard1
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app
    env_file: local.env